// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: monedas.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValorDia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fecha string  `protobuf:"bytes,1,opt,name=fecha,proto3" json:"fecha,omitempty"`
	Valor float32 `protobuf:"fixed32,2,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *ValorDia) Reset() {
	*x = ValorDia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monedas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValorDia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValorDia) ProtoMessage() {}

func (x *ValorDia) ProtoReflect() protoreflect.Message {
	mi := &file_monedas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValorDia.ProtoReflect.Descriptor instead.
func (*ValorDia) Descriptor() ([]byte, []int) {
	return file_monedas_proto_rawDescGZIP(), []int{0}
}

func (x *ValorDia) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *ValorDia) GetValor() float32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type MonedaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moneda       string `protobuf:"bytes,1,opt,name=moneda,proto3" json:"moneda,omitempty"`
	FechaInicio  string `protobuf:"bytes,2,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaTermino string `protobuf:"bytes,3,opt,name=fecha_termino,json=fechaTermino,proto3" json:"fecha_termino,omitempty"`
}

func (x *MonedaRequest) Reset() {
	*x = MonedaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monedas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonedaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonedaRequest) ProtoMessage() {}

func (x *MonedaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monedas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonedaRequest.ProtoReflect.Descriptor instead.
func (*MonedaRequest) Descriptor() ([]byte, []int) {
	return file_monedas_proto_rawDescGZIP(), []int{1}
}

func (x *MonedaRequest) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *MonedaRequest) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *MonedaRequest) GetFechaTermino() string {
	if x != nil {
		return x.FechaTermino
	}
	return ""
}

type MonedaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moneda  string      `protobuf:"bytes,1,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Valores []*ValorDia `protobuf:"bytes,2,rep,name=valores,proto3" json:"valores,omitempty"`
}

func (x *MonedaResponse) Reset() {
	*x = MonedaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monedas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonedaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonedaResponse) ProtoMessage() {}

func (x *MonedaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monedas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonedaResponse.ProtoReflect.Descriptor instead.
func (*MonedaResponse) Descriptor() ([]byte, []int) {
	return file_monedas_proto_rawDescGZIP(), []int{2}
}

func (x *MonedaResponse) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *MonedaResponse) GetValores() []*ValorDia {
	if x != nil {
		return x.Valores
	}
	return nil
}

type UpdateMonedaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moneda  string      `protobuf:"bytes,1,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Valores []*ValorDia `protobuf:"bytes,2,rep,name=valores,proto3" json:"valores,omitempty"`
}

func (x *UpdateMonedaRequest) Reset() {
	*x = UpdateMonedaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monedas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMonedaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonedaRequest) ProtoMessage() {}

func (x *UpdateMonedaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monedas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonedaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMonedaRequest) Descriptor() ([]byte, []int) {
	return file_monedas_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMonedaRequest) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *UpdateMonedaRequest) GetValores() []*ValorDia {
	if x != nil {
		return x.Valores
	}
	return nil
}

type UpdateMonedaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moneda string  `protobuf:"bytes,1,opt,name=moneda,proto3" json:"moneda,omitempty"`
	Status float32 `protobuf:"fixed32,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateMonedaResponse) Reset() {
	*x = UpdateMonedaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monedas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMonedaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonedaResponse) ProtoMessage() {}

func (x *UpdateMonedaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monedas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonedaResponse.ProtoReflect.Descriptor instead.
func (*UpdateMonedaResponse) Descriptor() ([]byte, []int) {
	return file_monedas_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMonedaResponse) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

func (x *UpdateMonedaResponse) GetStatus() float32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_monedas_proto protoreflect.FileDescriptor

var file_monedas_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x22, 0x36, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x6f,
	0x72, 0x44, 0x69, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x65, 0x63, 0x68, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x65, 0x63, 0x68, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x22, 0x6f, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x65, 0x63,
	0x68, 0x61, 0x5f, 0x69, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x66, 0x65, 0x63, 0x68, 0x61, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x65, 0x63, 0x68, 0x61, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x6f, 0x22, 0x55, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x44, 0x69, 0x61, 0x52,
	0x07, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x5a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x12, 0x2b, 0x0a, 0x07, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x64,
	0x61, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x44, 0x69, 0x61, 0x52, 0x07, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f,
	0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f,
	0x6e, 0x65, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x91, 0x01, 0x0a,
	0x0e, 0x50, 0x72, 0x65, 0x63, 0x69, 0x6f, 0x73, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x12,
	0x38, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x64,
	0x61, 0x73, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x64,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_monedas_proto_rawDescOnce sync.Once
	file_monedas_proto_rawDescData = file_monedas_proto_rawDesc
)

func file_monedas_proto_rawDescGZIP() []byte {
	file_monedas_proto_rawDescOnce.Do(func() {
		file_monedas_proto_rawDescData = protoimpl.X.CompressGZIP(file_monedas_proto_rawDescData)
	})
	return file_monedas_proto_rawDescData
}

var file_monedas_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monedas_proto_goTypes = []interface{}{
	(*ValorDia)(nil),             // 0: monedas.ValorDia
	(*MonedaRequest)(nil),        // 1: monedas.MonedaRequest
	(*MonedaResponse)(nil),       // 2: monedas.MonedaResponse
	(*UpdateMonedaRequest)(nil),  // 3: monedas.UpdateMonedaRequest
	(*UpdateMonedaResponse)(nil), // 4: monedas.UpdateMonedaResponse
}
var file_monedas_proto_depIdxs = []int32{
	0, // 0: monedas.MonedaResponse.valores:type_name -> monedas.ValorDia
	0, // 1: monedas.UpdateMonedaRequest.valores:type_name -> monedas.ValorDia
	1, // 2: monedas.PreciosMonedas.Query:input_type -> monedas.MonedaRequest
	3, // 3: monedas.PreciosMonedas.Update:input_type -> monedas.UpdateMonedaRequest
	2, // 4: monedas.PreciosMonedas.Query:output_type -> monedas.MonedaResponse
	4, // 5: monedas.PreciosMonedas.Update:output_type -> monedas.UpdateMonedaResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_monedas_proto_init() }
func file_monedas_proto_init() {
	if File_monedas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_monedas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValorDia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monedas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonedaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monedas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonedaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monedas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMonedaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_monedas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMonedaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_monedas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monedas_proto_goTypes,
		DependencyIndexes: file_monedas_proto_depIdxs,
		MessageInfos:      file_monedas_proto_msgTypes,
	}.Build()
	File_monedas_proto = out.File
	file_monedas_proto_rawDesc = nil
	file_monedas_proto_goTypes = nil
	file_monedas_proto_depIdxs = nil
}
